cross_compilation:
  stage: setup_enviroment
  image: ubuntu:20.04
  script:
    - apt-get update
    - apt-get install -y build-essential
    # install conda
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - conda init bash
    - conda env create -f environment.yml
    - conda activate onnx2fmu
    - onnx2fmu build onnx_models/stand_model.onnx