name: Build and test on self-hosted runners

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:

  build_and_test_windows:
    strategy:
      matrix:
        arch: [x86_64]
        os: [windows]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: [self-hosted, Windows]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas onnx jinja2 loguru typer fmpy cmake
          pip install -e .

      - name: Python unit tests
        run: |
          python -m unittest tests.test_variables
          python -m unittest tests.test_model
          python -m unittest tests.test_model_description
          python -m unittest tests.test_app

      - name: Build example4 FMI 2.0
        shell: cmd
        run: |
          set fmi_platform=${{ matrix.arch }}-${{ matrix.os }}
          onnx2fmu build ^
            tests/example4/example4.onnx ^
            tests/example4/example4Description.json ^
            target ^
            --fmi-platform %fmi_platform% ^
            --cmake-config Debug

  build_and_test_linux:
    strategy:
      matrix:
        arch: [x86_64]
        os: [linux]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: [self-hosted, Linux]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas onnx jinja2 loguru typer fmpy cmake
          pip install -e .

      - name: Python unit tests
        run: |
          python -m unittest tests.test_variables
          python -m unittest tests.test_model
          python -m unittest tests.test_model_description
          python -m unittest tests.test_app

      - name: Build example4 FMI 2.0
        shell: bash -l {0}
        run: |
          onnx2fmu build \
          tests/example4/example4.onnx \
          tests/example4/example4Description.json \
          target \
          --fmi-platform ${{ matrix.arch }}-${{ matrix.os }} \
          --cmake-config Debug
