name: Build the Reference FMUs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    strategy:
      matrix:
        include:
          - name: x86-windows
            image: windows-2022
            arch: x86
          - name: x86_64-windows
            image: windows-2022
            arch: x86_64
          - name: x86_64-linux
            image: ubuntu-20.04
            arch: x86_64
          - name: aarch64-linux
            image: ubuntu-20.04
            arch: aarch64
          # - name: x86_64-darwin
          #   image: macos-13
          #   arch: x86_64
          # - name: aarch64-darwin
          #   image: macos-13
          #   arch: aarch64
    runs-on: ${{ matrix.image }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          auto-activate-base: false

      - name: Build FMU
        shell: bash -l {0}
        run: |
          onnx2fmu build tests/models/gasifier.onnx
