name: Build and test the Reference FMUs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r onnx jinja2 loguru typer fmpy cmake
          pip install -e .

      - name: Python unit tests
        run: |
          python -m unittest tests.test_app

      - name: Build example1 FMU
        shell: bash -l {0}
        run: |
          onnx2fmu build tests/example1/example1.onnx tests/example1/example1Description.onnx

      - name: Build example2 FMU
        shell: bash -l {0}
        run: |
          onnx2fmu build tests/example2/example2.onnx tests/example2/example2Description.onnx
